import type { MaterialDoc } from '@aige/core';
import { color, Raw, str, TscnWriter, vec3 } from './tscn.ts';

export const GODOT_VERSION = '4.7.2';
export const GODOT_FEATURES = '4.7';

/** 'The Sidle of Milch' → 'SidleOfMilch' (C# assembly / csproj name). */
export function assemblyName(title: string): string {
  const words = title
    .replace(/^the\s+/i, '')
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean);
  const name = words.map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('');
  return /^[A-Za-z]/.test(name) ? name : `Game${name}`;
}

// Godot physical keycodes
const K = {
  W: 87,
  A: 65,
  S: 83,
  D: 68,
  E: 69,
  C: 67,
  SPACE: 32,
  SHIFT: 4194325,
  CTRL: 4194326,
  ENTER: 4194309,
  ESC: 4194305,
  UP: 4194320,
  DOWN: 4194322,
  LEFT: 4194319,
  RIGHT: 4194321,
};

const key = (code: number) =>
  `Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":${code},"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)`;
const mouse = (button: number) =>
  `Object(InputEventMouseButton,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"button_mask":0,"position":Vector2(0, 0),"global_position":Vector2(0, 0),"factor":1.0,"button_index":${button},"canceled":false,"pressed":false,"double_click":false,"script":null)`;
const joyButton = (button: number) =>
  `Object(InputEventJoypadButton,"resource_local_to_scene":false,"resource_name":"","device":-1,"button_index":${button},"pressure":0.0,"pressed":false,"script":null)`;
const joyAxis = (axis: number, value: number) =>
  `Object(InputEventJoypadMotion,"resource_local_to_scene":false,"resource_name":"","device":-1,"axis":${axis},"axis_value":${value.toFixed(1)},"script":null)`;

/** The input map from packages/godot/README.md (keyboard + mouse + gamepad). */
export const INPUT_ACTIONS: Record<string, string[]> = {
  move_forward: [key(K.W), key(K.UP), joyAxis(1, -1)],
  move_back: [key(K.S), key(K.DOWN), joyAxis(1, 1)],
  move_left: [key(K.A), key(K.LEFT), joyAxis(0, -1)],
  move_right: [key(K.D), key(K.RIGHT), joyAxis(0, 1)],
  sprint: [key(K.SHIFT), joyButton(7)],
  jump: [key(K.SPACE), joyButton(0)],
  crouch: [key(K.C), key(K.CTRL), joyButton(1)],
  interact: [key(K.E), joyButton(2)],
  attack: [mouse(1), joyAxis(5, 1)],
  skip: [key(K.SPACE), key(K.ENTER), key(K.ESC), joyButton(0)],
  pause: [key(K.ESC), joyButton(6)],
  look_left: [joyAxis(2, -1)],
  look_right: [joyAxis(2, 1)],
  look_up: [joyAxis(3, -1)],
  look_down: [joyAxis(3, 1)],
};

export const AUTOLOADS: [string, string][] = [
  ['Story', 'res://addons/aige/Story.cs'],
  ['Hud', 'res://addons/aige/Hud.cs'],
  ['Voice', 'res://addons/aige/Voice.cs'],
  ['Sfx', 'res://addons/aige/Sfx.cs'],
  ['Cutscenes', 'res://addons/aige/Cutscenes.cs'],
  ['AigeTest', 'res://addons/aige/Testing/AigeTest.cs'],
];

export interface ProjectGodotOptions {
  title: string;
  assembly: string;
  mainScene: string;
  width?: number;
  height?: number;
  icon?: string;
}

/** project.godot: application, autoloads, input map, Jolt physics and a realistic rendering setup. */
export function projectGodot(o: ProjectGodotOptions): string {
  const lines = [
    '; Engine configuration file.',
    '; Generated by AIGE (godot_export). Re-exporting rewrites it; change settings in project.json instead.',
    '',
    'config_version=5',
    '',
    '[application]',
    '',
    `config/name=${str(o.title)}`,
    `run/main_scene=${str(o.mainScene)}`,
    `config/features=PackedStringArray(${str(GODOT_FEATURES)}, "C#", "Forward Plus")`,
    ...(o.icon ? [`config/icon=${str(o.icon)}`] : []),
    '',
    '[autoload]',
    '',
    ...AUTOLOADS.map(([n, p]) => `${n}=${str(`*${p}`)}`),
    '',
    '[display]',
    '',
    `window/size/viewport_width=${o.width ?? 1920}`,
    `window/size/viewport_height=${o.height ?? 1080}`,
    'window/size/mode=2',
    'window/vsync/vsync_mode=1',
    '',
    '[dotnet]',
    '',
    `project/assembly_name=${str(o.assembly)}`,
    '',
    '[input]',
    '',
  ];
  for (const [action, events] of Object.entries(INPUT_ACTIONS)) {
    lines.push(`${action}={`, '"deadzone": 0.2,', `"events": [${events.join(', ')}]`, '}');
  }
  lines.push(
    '',
    '[physics]',
    '',
    '3d/physics_engine="Jolt Physics"',
    'common/physics_ticks_per_second=60',
    '',
    '[rendering]',
    '',
    'textures/default_filters/anisotropic_filtering_level=4',
    'anti_aliasing/quality/msaa_3d=2',
    'anti_aliasing/quality/use_taa=true',
    'lights_and_shadows/directional_shadow/size=8192',
    'lights_and_shadows/directional_shadow/soft_shadow_filter_quality=4',
    'lights_and_shadows/positional_shadow/soft_shadow_filter_quality=4',
    'lights_and_shadows/positional_shadow/atlas_size=8192',
    'environment/ssao/quality=3',
    'environment/ssil/quality=2',
    'environment/volumetric_fog/volume_size=128',
    'environment/volumetric_fog/volume_depth=128',
    'global_illumination/sdfgi/probe_ray_count=2',
    'environment/defaults/default_clear_color=Color(0, 0, 0, 1)',
    '',
  );
  return lines.join('\n');
}

/** The game's C# project (written once, then left to the user). */
export function csproj(assembly: string): string {
  return `<Project Sdk="Godot.NET.Sdk/${GODOT_VERSION}">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>${assembly}</RootNamespace>
  </PropertyGroup>
</Project>
`;
}

/** Windows export preset. AIGE JSON documents (cutscenes, voice lines) must ship with the game. */
export function exportPresets(assembly: string): string {
  return `[preset.0]

name="Windows Desktop"
platform="Windows Desktop"
runnable=true
advanced_options=false
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter="cutscenes/*.json, audio/voice/*.json"
exclude_filter="voices/*, scenes/*.scene.json"
export_path="build/${assembly}.exe"
patches=PackedStringArray()
encryption_include_filters=""
encryption_exclude_filters=""
seed=0
encrypt_pck=false
encrypt_directory=false
script_export_mode=2

[preset.0.options]

custom_template/debug=""
custom_template/release=""
debug/export_console_wrapper=1
binary_format/embed_pck=true
texture_format/s3tc_bptc=true
texture_format/etc2_astc=false
binary_format/architecture="x86_64"
application/product_name=${str(assembly)}
dotnet/include_scripts_content=false
dotnet/include_debug_symbols=false
dotnet/embed_build_outputs=false
`;
}

const res = (p: string) => (p.startsWith('res://') ? p : `res://${p}`);

/** A MaterialDoc as a Godot material (.tres). Packed AO/roughness/metal maps use ORMMaterial3D. */
export function materialTres(doc: MaterialDoc): string {
  const w = new TscnWriter();
  const tex = (p: string | undefined) =>
    p ? new Raw(`ExtResource(${str(w.ext('Texture2D', res(p)))})`) : undefined;
  const orm = tex(doc.ormMap);
  const [ru, rv] = doc.mapRepeat ?? [1, 1];
  const props = {
    transparency: doc.opacity < 1 ? 1 : undefined,
    cull_mode: doc.doubleSided ? 2 : undefined,
    vertex_color_use_as_albedo: doc.vertexColors ? true : undefined,
    albedo_color: color(doc.color, doc.opacity),
    albedo_texture: tex(doc.map),
    orm_texture: orm,
    roughness: doc.roughness,
    metallic: doc.metalness,
    emission_enabled: doc.emissive !== '#000000' ? true : undefined,
    emission: doc.emissive !== '#000000' ? color(doc.emissive) : undefined,
    emission_energy_multiplier: doc.emissive !== '#000000' ? doc.emissiveIntensity : undefined,
    normal_enabled: doc.normalMap ? true : undefined,
    normal_scale: doc.normalMap ? doc.normalScale : undefined,
    normal_texture: tex(doc.normalMap),
    ao_light_affect: orm ? 0.2 * doc.aoIntensity : undefined,
    uv1_scale: ru !== 1 || rv !== 1 ? vec3([ru, rv, 1]) : undefined,
  };
  return w.resource(orm ? 'ORMMaterial3D' : 'StandardMaterial3D', props);
}
